language: node_js
node_js:
- iojs
- '8'

after_script:

- scp  -o  StrictHostKeyChecking=no app.js  root@47.95.240.14:/home/www/root/

before_install:

- openssl aes-256-cbc -K $encrypted_cbedcb4c8d81_key -iv $encrypted_cbedcb4c8d81_iv
  -in  .travis/id_rsa.enc -out id_rsa -d

  - mv id_rsa ~/.ssh -f

- chmod 600  ~/.ssh/id_rsa

# 配置 ssh

- eval $(ssh-agent)

- ssh-add ~/.ssh/id_rsa

- cp .travis/ssh_config ~/.ssh/config
